name: Electric Sheep
favicon: null
layout_spectrum: 0.06426125136204064
typography_spectrum: 0.2508641150780022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8820584525819868
  lightness: 0.7615658848080784
  saturation: 0.0655896458774805
  rhythmicContrast: 0.5972713048104197
purpose: []
